In [41]:
import pandas as pd
import numpy as np

    # Load the dataset
df = pd.read_csv('../raw/Pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [42]:
# Contar la cantidad de valores nulos en cada columna
null_counts = df.isnull().sum()
print(null_counts)

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [43]:
# Rellenar los valores nulos con "None"
df_filled = df.fillna("None")
print(df_filled.isnull().sum())

#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [44]:
# Reordenar las columnas asi: pokedex_number,name,type1,type2,total,hp,attack,defense,sp_atk,sp_def,speed,generation,legendary
df_reordered = df_filled[['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']]
# Renombrar las columnas
df_renamed = df_reordered.rename(columns={
    '#': 'pokedex_number',
    'Name': 'name',
    'Type 1': 'type1',
    'Type 2': 'type2',
    'Total': 'total',
    'HP': 'hp',
    'Attack': 'attack',
    'Defense': 'defense',
    'Sp. Atk': 'sp_atk',
    'Sp. Def': 'sp_def',
    'Speed': 'speed',
    'Generation': 'generation',
    'Legendary': 'legendary'
})
df_renamed.head()

,pokedex_number,name,type1,type2,total,hp,attack,defense,sp_atk,sp_def,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,None,309,39,52,43,60,50,65,1,False

In [45]:
# hacer que la columna pokedex_number no repita el mismo numero, es decir, que cada pokemon tenga un numero unico
df_renamed = df_renamed.drop_duplicates(subset=['pokedex_number'])
df_renamed.head()

,pokedex_number,name,type1,type2,total,hp,attack,defense,sp_atk,sp_def,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,None,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,None,405,58,64,58,80,65,80,1,False

In [46]:
# Guardar el DataFrame limpio en un nuevo archivo CSV
df_renamed.to_csv('../processed/cleaned_pokemon.csv', index=False)